### ISSUE TITLE
error TS6196: my test class is declared but never used

### ISSUE THREAD

**Issue by ripper234** [pana-cc/mocha-typescript#113]
I tried the quickstart guide, defined a test class, and am getting `declared but never used` errors on my test file.

Here is my `package.json`:

```
{
  "name": "hanoi",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.ts",
    "test": "mocha -r ts-node/register src/*.test.ts"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^10.7.1",
    "chai": "^4.1.2",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.14.0",
    "mocha": "^5.2.0",
    "mocha-typescript": "1.1.17",
    "tslint": "^5.11.0"
  },
  "dependencies": {
    "@types/chai": "^4.1.4",
    "@types/mocha": "5.2.5",
    "ts-node": "^7.0.1",
    "typescript": "^3.0.1"
  }
}
```

And my HanoiTest file:

```
import { Hanoi } from "./hanoi";
import { expect } from "chai";
import { suite, test } from "mocha-typescript";

@suite
class HanoiTests {
  @test
  solve1() {
    const hanoi = new Hanoi(1);
    expect(hanoi.solve()).to.equal(1);
  }

  @test
  solve2() {
    const hanoi = new Hanoi(2);
    expect(hanoi.solve()).to.equal(3);
  }

  @test
  solve3() {
    const hanoi = new Hanoi(3);
    expect(hanoi.solve()).to.equal(7);
  }
}
```

The error I'm getting:

```
i>yarn test
yarn run v1.9.4
$ mocha -r ts-node/register src/*.test.ts

C:\work\hanoi\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/hanoi.test.ts(6,7): error TS6196: 'HanoiTests' is declared but never used.

    at createTSError (C:\work\hanoi\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\work\hanoi\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (C:\work\hanoi\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (C:\work\hanoi\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\work\hanoi\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\work\hanoi\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\work\hanoi\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\work\hanoi\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\work\hanoi\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

**Comment by pana-cc** [comment]
I am sorry but I can not reproduce this issue.
