### ISSUE TITLE
Unable to compile TypeScript when use typescript 2.4.0

### ISSUE THREAD

**Issue by ruiming** [pana-cc/mocha-typescript#34]
```typescript
import { test as testFn } from 'app'
import { assert } from 'chai'
import { suite, test } from 'mocha-typescript'

@suite class Test {
  @test testMethod (): void {
    assert.deepEqual(NaN, NaN)
    assert.equal(testFn(2), 2)
  }
}
```
Throw error in typescript2.4.0
```
nyc mocha --compilers ts:ts-node/register -r tsconfig-paths/register src/test --ui mocha-typescript --require source-map-support/register --timeout=60000


/home/ruiming/Documents/typescript-starter/node_modules/ts-node/src/index.ts:300
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/test/test.ts (7,2): Argument of type 'typeof Test' is not assignable to parameter of type 'SuiteTrait'.
  Type 'typeof Test' provides no match for the signature '(this: ISuiteCallbackContext, ctx: ISuiteCallbackContext, ctor: Function): void'. (2345)
    at getOutput (/home/ruiming/Documents/typescript-starter/node_modules/ts-node/src/index.ts:300:15)
    at /home/ruiming/Documents/typescript-starter/node_modules/ts-node/src/index.ts:330:16
    at Object.compile (/home/ruiming/Documents/typescript-starter/node_modules/ts-node/src/index.ts:489:17)
...
```
but work fine in typescript 2.3.4

**Comment by pana-cc** [comment]
Hi @ruiming,
Hope all is well with `+ mocha-typescript@1.1.5`. Could you give it a try?

I am closing this issue as I've moved the whole project (code + tests) to typescript 2.4.0. The new version introduced covariant checking for callback parameters. I guess this is what failed the type checking. I couldn't figure a nice way to preserve both the call overloads with single trait (e.g. the result of slow() and timeout()) and the ClassDecorator like signature here: https://github.com/pana-cc/mocha-typescript/blob/bfefa2d7a09385c981503bedbf31cf5aa0fcc5d1/index.d.ts#L42 so I had to go for an `any`.

**Comment by ruiming** [comment]
Upgrade mocha-typescript solved the problem. Thanks.
